openapi: 3.0.0
info:
  title: E-commerce api
  description:
  version: 1.0.0
  contact:
    email: vishnukulkarni4302@gmail.com
    url: "https://github.com/Fierce-Black-Dragon"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1

        default: v1
      protocol:
        enum:
          - http
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /:
    get:
      summary: greets the  user.
      description:
      responses:
        "200": # status code
          description: A object
          content:
            application/json:
              schema:
                type: object

                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /signup:
    post:
      summary: user sign up
      description: Registering the user  to our store /database
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - file
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                file:
                  in: formData
                  description: The uploaded file data
                  type: file
                  format: binary
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string

        400:
          description: Bad request
        500:
          description: internal server error
  /login:
    post:
      tags:
        - auth
      summary: login
      consumes:
        - application/json
      produces:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean

                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string

        400:
          description: Bad request
        500:
          description: internal server error
